version: '3.8'

services:
  git-remote-mcp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/workspace
      - ./config:/config:ro
    environment:
      - GIT_CONFIG_GLOBAL=/config/gitconfig
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge